spring.application.name=LibraryManagementSystem

spring.datasource.url=${jdbc:mysql://mysql-34eb39fd-abhay506882-fb22.j.aivencloud.com:17210/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${avnadmin}
spring.datasource.password=${AVNS_Tdn6S6ggoWCzuzBR4Eg}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}
server.address=0.0.0.0

spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp
